---
version: 2
multicolumn: false
web-width: 500px
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/153149/articles/167393/master/file/figures/TZ_map1/TZ_map1.png"
    path: figures/TZ_map1/TZ_map1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
